### ISSUE TITLE
Modified name scheme

### ISSUE THREAD

**Issue by amoghe** [tonistiigi/dnsdock#12]
dnsdock has been quite useful, thank you for contributing it to the OSS community.

Currently dnsdock automagically registers names with this scheme:

`<anything>.<container-name>.<image-name>.<environment>.<domain>`

However, in my case the `image-name` doesn't really make sense. For example, I have a zookeeper image that is used to spawn a cluster (of 3 containers), and I'd prefer their names be `zookeeper[n].staging.example.com` (e.g. zookeeper2.staging.example.com). The same is true of other containers as well (e.g. kafka1.development.example.com). To this end, is there a way to skip over the image-name part altogether? Alternatively, is there an environment variable that we can set which would completely override this scheme and allow dnsdock to register an arbitrary name for a container? (Would you accept PRs for either of these?)

**Comment by tonistiigi** [comment]
Yes, you can override from environment variables. `DNSDOCK_IMAGE ` or `SERVICE_NAME` do that. See a4fd3a340e6566d5b354c718b1ca49769ab0d90f

You are welcomed make this even simpler. Just don't break current defaults. I think when image name and container name don't match we can make the image part completely optional.

So `redis1.redis.docker` and `redis1.docker` point to same container. But when you create an image `redis1` then they start pointing to different containers.

**Comment by amoghe** [comment]
I'm afraid allowing more combinations (of container_name and image_name) is going to make things more confusing rather than simpler.

The simplest option forward might be to allow completely arbtirary dns names via a new env var e.g. ```DNSDOCK_FQDN=foo.bar.com``` will cause the container name to be registered exactly like that (irrespective of its container_name or image_name). With this option, dnsdock makes no attempt to resolve conflicts and developers are expected to know what they're doing.

Would something like this makes sense to you?

**Comment by amoghe** [comment]
In order to achieve my goal (without modifying any source code for dnsdock), I tried to launch the container using the following options

`-e "DNSDOCK_NAME=foobar" -e "DNSDOCK_IMAGE="` 

Basically I was trying to get dnsdock to ignore the image name. This resulted in the following image being registered:

```
   "00c925edb10197474bb586d3bfcb01a968feba6ce5966a1fffeb6c2cea7263e6" : {
      "Image" : "",
      "Name" : "foobar",
      "Ttl" : -1,
      "Ip" : "172.17.0.13"
   }
```

However queries for this name (`foobar.<environment>.<domain>`) do not succeed, I believe it is because of this code:

```
for _, service := range s.services {
			tests := [][]string{
				s.config.domain,
				strings.Split(service.Image, "."),
				strings.Split(service.Name, "."),
			}

			for i, q := 0, query; ; i++ {
				if len(q) == 0 || i > 2 {
					c <- service
					break
				}

				var matches bool
				if matches, q = matchSuffix(q, tests[i]); !matches {
					break
				}
			}

		}
```

In this case, the `service.Image` will be an empty string, and the matchSuffix will not succeed. 

If I understand correctly, the simplest fix is to filter out empty strings from the `tests` array, but I'm not sure if that would break anything else.  Alternatively, maybe we want to handle empty `service.Image` names specially (and not allow empty `service.Name` strings). Thoughts?

**Comment by tonistiigi** [comment]
I think skipping empty images should fix it. Make sure you add a test also.
