### ISSUE TITLE
cant get resolver to work

### ISSUE THREAD

**Issue by brpaz** [tonistiigi/dnsdock#19]
HI.
I trying to setup dnsdock and I have the container running  but when I run ```curl http://dnsdock.docker/services``` I get the following error:

```
curl: (6) Could not resolve host: dnsdock.docker
```

When i run ```dig .docker``` I get : " no matches found: *.docker"

I am using linux mint 17 and here is my /etc/resolv.conf:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search lan
nameserver 172.17.42.1
```

What I am doing wrong?

**Comment by PabloCastellano** [comment]
nameserver 172.17.42.1 must be placed before nameserver 127.0.0.1

**Comment by brpaz** [comment]
yeah, I thought about it too, but i couldnt figure it out  how to put it before, since /etc/resolv.conf is dynamically generated. I added to "/etc/resolvconf/resolv.conf.d/head" and after some tries it start working.

Thank you.
