### ISSUE TITLE
Containers can't use dnsdock service

### ISSUE THREAD

**Issue by mpeters** [tonistiigi/dnsdock#41]
I can't tell if I'm doing something wrong, or if I've found a bug. I'm just trying to get my containers to use the dnsdock service, but for some reason it's always timing out. First, my /etc/resolv.conf on my host:

    $ cat /etc/resolv.conf
    nameserver 172.17.42.1
    search docker

I start up the dnsdock container:

    $ docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.42.1:53:53/udp tonistiigi/dnsdock

It's up and running:

    $ docker ps
    CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS                    NAMES
    55e19490f1b3        tonistiigi/dnsdock   "/go/bin/dnsdock"   2 seconds ago       Up 1 seconds        172.17.42.1:53->53/udp   dnsdock

And I can ping that container by hostname on my host:

    $ host dnsdock
    dnsdock.docker has address 172.17.0.3
    dnsdock.docker mail is handled by 0 dnsdock.docker.

And it shows up just in the REST request:

```
$curl -s http://dnsdock.docker/services | jq .
{
      "55e19490f1b304636857d9c19f6df7c5a1a20917d7d06e25a54a0256cc5f83d0": {
    "Aliases": [],
    "Ttl": -1,
    "Ip": "172.17.0.3",
    "Image": "dnsdock",
    "Name": "dnsdock"
  }
}
```

Now, I start up a 2nd container to use that dns:

    $ docker run -i -t --dns=172.17.42.1 centos:centos6 /bin/bash

DNSDock see it:

```
curl -s http://dnsdock.docker/services | jq .
{
  "bc187c9ca3a220586ecdeeb9314c69a85be60eecdd96b9a00c8f9a8c355008a6": {
    "Aliases": [],
    "Ttl": -1,
    "Ip": "172.17.0.4",
    "Image": "centos",
    "Name": "sleepy_archimedes"
  },
  "55e19490f1b304636857d9c19f6df7c5a1a20917d7d06e25a54a0256cc5f83d0": {
    "Aliases": [],
    "Ttl": -1,
    "Ip": "172.17.0.3",
    "Image": "dnsdock",
    "Name": "dnsdock"
  }
}
```

And the /etc/resolv.conf inside the new container looks ok:

```
root@bc187c9ca3a2 /]# cat /etc/resolv.conf
nameserver 172.17.42.1
search docker
```

But when I try to use it it just hangs and then eventually times out:

```
[root@bc187c9ca3a2 /]# host dnsdock.docker
;; connection timed out; trying next origin
;; connection timed out; no servers could be reached
```

So what am I doing wrong? Thanks.

**Comment by rarkins** [comment]
I use docker-compose and in my case all containers have this configuration:

`    dns: 172.17.42.1`

I do not configure the host's `/etc/resolv.conf`

**Comment by mpeters** [comment]
Configuring the host's dns is just to show that the dns server works and is getting updated as new containers show up.

I've tried docker-compose as well, I was just showing the simplest example that doesn't work using just docker commands. There should be no difference between using the `dns` option in a docker-compose file vs the `--dns` option on docker run command.

**Comment by mpeters** [comment]
Btw, this is on CentOS7. I've tried docker versions 1.6.1 and 1.7.1

**Comment by mpeters** [comment]
I just tried on Ubuntu 14.04 with docker 1.6.2 and it does work. So something either about those version numbers or something about CentOS7 itself... Not sure

**Comment by mpeters** [comment]
Sorry, user error. Something about the default settings of firewalld in CentOS 7 is blocking the dns request from inside one container to the docker bridge. Turning off the firewall fixes it (will investigate actual rules so that I can turn it back on).
