### ISSUE TITLE
Enable multiple DNS forwarders

### ISSUE THREAD

**Issue by diogogmt** [tonistiigi/dnsdock#43]
I'm having an issue setting the dnsdock nameserver as my primary DNS server.
I need to be able to forward the DNS queries for our internal private domains through dnsdock.

For example:

my /etc/resov.conf file:

```
nameserver 192.168.99.100 **DNSDOCK host container IP
nameserver 10.191.1.5
nameserver 10.180.1.5
```

If I try to resolve a name like ```jenkins01.service.cloud``` I get back a name conflict IP 127.0.53.53
```
Server:    192.168.99.100
Address 1: 192.168.99.100

Name:      jenkins01.service.cloud
Address 1: 127.0.53.53
```

Is there any other way to resolve this issue?

**UPDATED**
In the readme file it lists there is a option to specify a different fallback DNS server ```-nameserver="8.8.8.8:53": DNS server for unmatched requests```
Is that nameserver option configured by environment variables?

**UPDATED**
I figured it out, the nameserver can be specified as an argument when running the docker container

My question now is:
Can you support multiple DNS forwarders?

**Comment by kgutwin** [comment]
Is this a duplicate of #29?

**Comment by diogogmt** [comment]
@kgutwin true, I'll close this ticket then.

**Comment by Kampfbereit** [comment]
Hmm, these two issues reference each other and are both closed. I would also like multiple DNS forwarders. On my current external test-system, 8.8.8.8 is blocked so I need to use 2 internal nameservers over there. Those internal nameservers doesn't work when I fire it up on my local machine which means I need to have 2 different docker-compose.yml files for these two systems. 
Having a swich that reads "-nameserver 191.12.11.10:53,192.12.11.8:53,8.8.8.8:53" would be real nice.
