### ISSUE TITLE
dnsdock on Windows 7?

### ISSUE THREAD

**Issue by criffle** [tonistiigi/dnsdock#53]
I saw Weave doesn't work with Docker on Windows - and was interested in using dnsdock for Docker that's installed on Windows.  Is this possible or recommended?  Thanks so much

**Comment by tjamet** [comment]
Would #62 solve this issue?

**Comment by aacebedo** [comment]
On windows 7 I don't know as M$ does not support it anymore
I think docker machine shall be working.
If you want to test it, you're welcome !

**Comment by beatcracker** [comment]
My 2¢.

I couldn't make `dnsdock` work on Docker Toolbox.  While `nslookup` is able to resolve domain name to ip, anything else, like `ping` or browsers, report that domain name couldn't be found.

**Comment by aacebedo** [comment]
did you changed your system wide dns ?

**Comment by beatcracker** [comment]
Yes, this happens when I set `docker-machine` VM address as DNS server in connection properties. I haven't had time to look at it properly (packet sniffer, etc...) yet.

**Comment by aacebedo** [comment]
other users of dnsdock previously mentioned that docker machine still have sone issue on the network side. Keep me posted about your investigations !

**Comment by beatcracker** [comment]
Changing DNS server for VirtualBox's  adapter that is in the same subnet as IP-address reported by `docker-machine` worked for me.

![DNS server](https://cloud.githubusercontent.com/assets/7583050/21098080/958d6d80-c078-11e6-8ca6-71f41b6f5c98.PNG)
