### ISSUE TITLE
docker-compose version 2 service definiton breaks dnsdock

### ISSUE THREAD

**Issue by ruimarinho** [tonistiigi/dnsdock#59]
dnsdock is unable to register containers running inside the new [network groups](https://docs.docker.com/compose/networking/) of docker-compose version 2.

Logs show the following (notice the `<nil>`):

```
2016/02/22 00:41:39 Added service: d90f35986816e301f2144ebc0ec97c159cc8da741ef34b3fb1ac9f65a3d26719 {name_foo_1 bar1 <nil> -1 []}
```

**Comment by Buinskii** [comment]
+1

**Comment by Buinskii** [comment]
+1

**Comment by tjamet** [comment]
I had a look at how to solve this issue, it appears that dockerclient does not support it by default.
There is an update on my fork that solves this issue: https://github.com/tjamet/dnsdock/tree/networks however, I cannot do the pull request until dockerclient supports more recent API (PR: https://github.com/samalba/dockerclient/pull/234)
Maybe you can try the fix by running `docker run <...> tjamet/dnsdock`?

**Comment by maaarghk** [comment]
That looks good - hopefully dockerclient will accept the PR soon.

In the meantime does anyone know of a workaround?

**Comment by jnugh** [comment]
@tjamet I use:

`network_mode: "bridge"`

 for the services that should be available via dns.

**Comment by paolomainardi** [comment]
@tjamet i tried your docker image, it does not correcly detect the ips of containers running inside a docker-compose network, i see just "nil".

@tjamet do you have any plans to solve this issue ?

Thanks a lot!

**Comment by duck1123** [comment]
@paolomainardi I had the same problem and was able to fix that by applying this patch. https://github.com/duck1123/dnsdock/commit/bbf2279715e3aa3a0e4907bea6c82f4844bae06a

I'm not sure if it's the best solution, but it allowed me to specify dns aliases for services that only exist in a docker network. A proper solution would probably allow the user to specify which network adapter to use in cases like this.

**Comment by paolomainardi** [comment]
Thanks @duck1123!

AFAIK a container can exisr just in a network, am wrong ?

**Comment by paolomainardi** [comment]
@tonistiigi should we consider this project dead ? is there anything we can do to fix the docker networks compatibility ?

**Comment by paolomainardi** [comment]
The answer is pretty obvious, it's time to look for an alternative.

**Comment by tjamet** [comment]
Sorry for the late reply @paolomainardi 
I also run docker-compose with networks and do not notice any problem
There are nil in logs but dig answers correctly with <service>.<network>.<domain>

**Comment by james-nesbitt** [comment]
currently this seems stalled by the samalba client.  Should we consider re-writing this to use the fsouza dockerclient base instead?  It's quite active in development.

**Comment by koddo** [comment]
@jnugh, adding `network_mode: "bridge"` works for me, thanks

**Comment by aacebedo** [comment]
Hi

I did some modification to remove dependencies to deprecated docker client lib. 
I've replaced the samalba library by the official docker client one.
Tested on my environment with a compose file creating containers with networks (no nil ip address anymore).

**Comment by mryan43** [comment]
I can confirm that aacebedo's fork works perfectly with docker-compose v2 ! I didn't find it on docker hub so I had to build it myself.

**Comment by paolomainardi** [comment]
Thanks a lot @aacebedo can you build it on the docker hub ?

**Comment by aacebedo** [comment]
Hi !
You're welcome :)
I've pushed the image with the following tag on dockerhub:  aacebedo/dnsdock:1.12.1 
A docker pull shall do the trick.

I do not have the ownership on the official repository so I am unable to push it as an official dnsdock release.
I hope the author will merge my PR and will update its image, as people has to change the name of the repo in their workflow with the current solution :(

**Comment by james-nesbitt** [comment]
it works for me.

I am surprised that the official image isn't set to rebuild on merge.

**Comment by aacebedo** [comment]
Travis can be configured to push automatically. 
I'll check with @tonistiigi if I can push to my docker hub repo instead of his as he said he don't use the code anymore.

**Comment by greg0ire** [comment]
>  I'll check with @tonistiigi if I can push to my docker hub repo instead of his as he said he don't use the code anymore. 

You can also configure hub.docker.com to build on each merge instead of letting Travis do it, which is quite easy. Maybe he could do that instead, so that the image name stays the same?

**Comment by aacebedo** [comment]
I've migrated on Rocker so hub.docker is not an option anymore

**Comment by greg0ire** [comment]
Maybe @tonistiigi could add you as a collaborator on hub.docker.com so that you can push the image manually ? That way the name of the image does not change…

**Comment by aacebedo** [comment]
Already did it but it still cannot erase or have a total control on the repo

**Comment by greg0ire** [comment]
Another solution would be embrace the name change and update the documentation to reflect the fact that `aacebedo/dnsdock` should be used because it is more maintained.

**Comment by aacebedo** [comment]
Yep I am going to ask him
