### ISSUE TITLE
Build in a busybox image?

### ISSUE THREAD

**Issue by smerrill** [tonistiigi/dnsdock#6]
Thank you so much for dnsdock - it's a great service and I make heavy use of it.

That said, it would be great if there were builds of it that were based on a lighter-weight container so that this 8 MB binary doesn't pull down 400 MB of Debian and golang layers just to run a statically-linked binary.

(I've solved that internally by building dnsdock and putting it into a busybox image.)

What would you think about shipping an official container based on something very lightweight, like progrium/busybox or https://registry.hub.docker.com/_/busybox/?

**Comment by tonistiigi** [comment]
Yeah, I share your pain and I'm pushing docker/docker#8021 to have a solution for that. This repo also has a nested-build branch uses this.

I haven't made the busybox image default because I think there's a lot of added value with having a trusted build.

I could probably make a `tonistiigi/dnsdock-minimal` image until there is a better solution.

**Comment by t3dev** [comment]
+1 to provide a slim runtime container

**Comment by khena** [comment]
+1 :)
maybe with the alpine distribution? alpine include golang package (like the kiasaki/alpine-golang dockerfile)

**Comment by rarkins** [comment]
@tonistiigi it's not possible to build in a smaller image until changes to docker itself are made?

**Comment by bersace** [comment]
What if you just drop a .deb or something built elsewhere than in the docker build step ?

**Comment by IxDay** [comment]
For my use case I ended up building an image on alpine.
If you are interested, I made a pull request which modify the Dockerfile accordingly.

**Comment by aacebedo** [comment]
Done with alpine
