### ISSUE TITLE
Set content-type header to json

### ISSUE THREAD

**Issue by greg0ire** [tonistiigi/dnsdock#68]
Doing this should make the result display nicely, especially if you have something like [JsonView](https://jsonview.com/) installed.

**Comment by aacebedo** [comment]
On which function ?

**Comment by greg0ire** [comment]
I don't know about the code, but it should be done on the response for the `http://dnsdock.docker/services` page, for instance.

**Comment by aacebedo** [comment]
Ok you're talking about the http server to access records. I'll check this out asap

**Comment by greg0ire** [comment]
Possible solution : http://stackoverflow.com/a/12830156/353612

**Comment by greg0ire** [comment]
I tried that and `w.Header().Set("X-toto", "Y")`, but nothing changes… any idea what might go wrong?

**Comment by aacebedo** [comment]
Can you add that in the getServices function before the call to the Encode method:
```
w.Header().Set("Content-Type", "application/json; charset=UTF-8")
w.WriteHeader(http.StatusOK)
```

**Comment by greg0ire** [comment]
Trying rightaway!

**Comment by aacebedo** [comment]
If this is working do not hesitate to do a pull request !
Please create a "features/set_content-type_header" branch to do so

**Comment by greg0ire** [comment]
I'm planning on it, but… it does not seem to have any effect.

**Comment by greg0ire** [comment]
I have something that works ;) PR coming soon

**Comment by aacebedo** [comment]
Tried the modifications on the getServices method and checked the header with curl, It is working.

**Comment by greg0ire** [comment]
Can you try moving the two lines after the if clause? I tried and it does not work, and using this header for the error message makes no sense, does it?

**Comment by aacebedo** [comment]
Arf I've just pushed the modifications on the develop branch

**Comment by aacebedo** [comment]
Can you tell me if it is working on your side ?

**Comment by greg0ire** [comment]
How do I get the container for the develop branch?

**Comment by aacebedo** [comment]
go to your clone dir and checkout the develop branch then execute the same rocker command we used earlier

**Comment by greg0ire** [comment]
oh ok!

**Comment by greg0ire** [comment]
Works like a charm : 
![json](https://cloud.githubusercontent.com/assets/657779/18171731/43df1bba-7063-11e6-9480-03c3caa9228d.png)
