### ISSUE TITLE
adding additional CNAME records

### ISSUE THREAD

**Issue by t3dev** [tonistiigi/dnsdock#8]
First of all thx for providing dnsdock, it's a nice tool to add simple dns/service discovery inside docker.

For my use case I would like to add *multiple* hostname/aliases to a single running container. For this reason I'd like to be able to add "arbitrary" CNAME records into dns. 

Does this sound like a valid use case for dnsdock?
Is this something that is supported by dnsdock already or something you could imagine to add?

**Comment by tonistiigi** [comment]
You can add aliases or arbitrary responses with the HTTP server but A records are only supported. I'm ok to adding CNAME if you are willing to maintain it. But maybe then it would make sense to make a separate project that has the DNS/HTTP server logic and is included as a package by `dnsdock` that adds the docker specific features.

**Comment by tonistiigi** [comment]
Just spotted a fork of this project that seems to have some alias functionality. https://github.com/t0mk/dnscock

**Comment by t3dev** [comment]
thx for your quick response. Actually CNAME is not my main concern, so additional A-records are probably fine as well. The most important is probably the ease of maintenance vi ENV varibles like DNSDOCK_ALIAS or similar. This seems to be a good a idea.

**Comment by K-Phoen** [comment]
Since #16 has been merged, this issue can be closed :)
